# Generated by Django 4.2.21 on 2025-05-29 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Gastos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_do_gasto', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qtd_parcelas', models.IntegerField()),
                ('descricao', models.CharField(max_length=30)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fk_nome_cartao', to='cards.cartao')),
                ('quem_gastou', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cards.pessoa')),
            ],
        ),
    ]
