# Generated by Django 4.2.21 on 2025-05-29 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartao',
            old_name='name',
            new_name='nome',
        ),
    ]
