# Generated by Django 4.2.21 on 2025-05-29 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_rename_name_cartao_nome'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gastos',
            new_name='Gasto',
        ),
    ]
