# Generated by Django 4.2.21 on 2025-05-31 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_rename_gastos_gasto'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasto',
            name='categoria',
            field=models.CharField(choices=[('despesas_fixas', 'Despesas Fixas'), ('despesas_variaveis', 'Despesas Variáveis'), ('alimentacao', 'Alimentação'), ('educacao', 'Educação'), ('assinatura', 'Assinatura'), ('lazer', 'Lazer'), ('relacionamento', 'Relacionamento'), ('manutencao', 'Manutenção'), ('financeiro', 'Financeiro')], default='outros', max_length=20),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='quem_gastou',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_nome_pessoa', to='cards.pessoa'),
        ),
    ]
