# Generated by Django 4.2.21 on 2025-06-02 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_cartao_criado_em_gasto_criado_em_pessoa_criado_em'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='gasto',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
